#builk-stage
FROM daocloud.io/library/maven:3.6.1-jdk-8-slim AS build
WORKDIR /usr/src

COPY ./src ./src
COPY ./pom.xml ./pom.xml
## import data
# ADD ./schema.sql /schema.sql
# ADD ./m2/.m2 /root/.m2
RUN mvn clean package

#final-stage
FROM tomcat:9
COPY --from=build /usr/src/target/sport.war /usr/local/tomcat/webapps/sport.war
