version: "3.4"
# COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
services:
  api:
    image: api:latest
    container_name: api
    build:
      context: ../.
      dockerfile: ./Docker/Dockerfile
    volumes:
      - ../target:/var/tmp
