version: "3.4"
# COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
services:
  api:
    image: zelejs/allin-web:jdk11
    container_name: api
    volumes: 
      #- ./api/config/application.yml:/webapps/config/application.yml
      - ./api/config/application-test.yml:/webapps/config/application-test.yml
      - ./api/app.jar:/webapps/app.jar
    #command:
    #  - /usr/local/bin/run.sh
    #  - produce
    #ports: 
    #  - 8080:8080

networks: 
  default:
    external: 
      name: sandbox_network

