version: "3.4"
services:
  maven:
    image: maven:3.6.0-jdk-11-slim
    container_name: mvn_sandbox
    working_dir: /usr/src
    volumes: 
      - ./api:/usr/src
      - m2:/root/.m2

volumes:
  m2:
    