version: "3.4"
services:
  maven:
    image: maven:3.6.0-jdk-11-slim
    container_name: mvn_sandbox
    working_dir: /usr/src
    volumes: 
      - m2:/root/.m2
      - ./m2/settings.xml:/root/.m2/settings.xml
      - ./api:/usr/src

volumes:
  m2:
    