version: "3.4"
services:
  db: 
    container_name: api:db
    image: 'daocloud.io/library/mysql:5.7'
    privileged: true
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysql.conf.d/sql_mode.cnf:/etc/mysql/mysql.conf.d/sql_mode.cnf
      - ./mysql/sandbox-schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks: 
      - db_network

networks: 
  default:
    db_network:
