version: "3.4"
# COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
services:
  api:
    image: api:sandbox
    container_name: api_sandbox
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes: 
      - ./config/application-dev.yml:/webapps/config/application-dev.yml
    ports: 
      - 8080:8080
    networks: 
      - app_default
      - mysqlserver_default
      
  tool:  #docker-compose run --rm tool ping api
    image: busybox:latest
    networks: 
      - app_default
      - mysqlserver_default
  
networks: 
  app_default:
    external: true
  mysqlserver_default: 
    name: mysqlserver_default
    external: true
